export const allInvestigations = 

[
{ name:"Fluorescein angiography"},
{ name:"Auto Fluorescence"},
{ name:"Fundus photography"},
{ name:"Ultrasonography"},
{ name:"UBM"},
{ name:"OCT Macula"},
{ name:"OCT Optic nerve"},
{ name:"Anterior segment OCT"},
{ name:"OCT Angiography Retina"},
{ name:"OCT Angiography Optic nerve"},
{ name:"OCT Angiography unspecified"},
{ name:"Pentacam"},
{ name:"Pachymetry"},
{ name:"Visual field"},
{ name:"ERG"},
{ name:"VEP"},
{ name:"VEP flash & pattern"},
{ name:"EOG"},
{ name:"VEP Multi Focal"},
{ name:"ERG Multi Focal"},
{ name:"Sweep VEP"},
{ name:"EEG"},
{ name:"EEG long"},
{ name:"EMG one muscle"},
{ name:"EMG two muscles"},
{ name:"EMG three muscles"},
{ name:"EMG four muscles"},
{ name:"Specular Microscopy"},
{ name:"Optical Biometry"},
{ name:"VEP + ERG"},
]

